---
# For LDAP Install Base Part
PACKAGES_SERVER:
  - openldap
  - compat-openldap
  - openldap-servers
  - openldap-clients
  - openldap-servers-sql
  - openldap-devel

PACKAGES_CLIENTS:
  - openldap-clients
  - nss-pam-ldapd

CHRONY_NTP: 0

NETWORK_NET_SERVER:
  - s2c.time.edu.cn
  - s2m.time.edu.cn
  - 0.cn.pool.ntp.org
  - 3.cn.pool.ntp.org
  - 0.centos.pool.ntp.org
  - 3.centos.pool.ntp.org

SERVER_FQDN: laoshiren.ldapserver.com


